### ISSUE TITLE
Camera Take Issue

### ISSUE THREAD

**Issue by MFennig** [BrainPad/FindYourCandy#10]
Hey,

So have the webapp running, but when we go to :18000/learn, then click the "Start" button, we get this error:

2017-03-01 17:31:45,972 - gensim.models.doc2vec - DEBUG - Fast version of gensim.models.doc2vec is being used
2017-03-01 17:31:45,976 - summa.preprocessing.cleaner - INFO - 'pattern' package not found; tag filters are not available for English
2017-03-01 17:31:45,984 - candysorter.models.texts - INFO - *** FakeTextAnalyzer loaded. ***
2017-03-01 17:31:45,984 - candysorter.models.texts - INFO - Loading labels...
2017-03-01 17:31:45,984 - candysorter.models.texts - INFO - Finished loading labels.
2017-03-01 17:31:45,985 - candysorter.models.images.classify - INFO - Loading inception model...
2017-03-01 17:31:46,570 - candysorter.models.images.classify - INFO - Finished loading inception model.
2017-03-01 17:31:46,572 - candysorter.models.images.classify - INFO - Loading transfer model...
2017-03-01 17:31:46,952 - candysorter.models.images.classify - INFO - Finished loading transfer model.
 * Running on http://0.0.0.0:18000/ (Press CTRL+C to quit)
 * Restarting with stat
2017-03-01 17:31:49,034 - gensim.models.doc2vec - DEBUG - Fast version of gensim.models.doc2vec is being used
2017-03-01 17:31:49,037 - summa.preprocessing.cleaner - INFO - 'pattern' package not found; tag filters are not available for English
2017-03-01 17:31:49,045 - candysorter.models.texts - INFO - *** FakeTextAnalyzer loaded. ***
2017-03-01 17:31:49,045 - candysorter.models.texts - INFO - Loading labels...
2017-03-01 17:31:49,045 - candysorter.models.texts - INFO - Finished loading labels.
2017-03-01 17:31:49,046 - candysorter.models.images.classify - INFO - Loading inception model...
2017-03-01 17:31:49,631 - candysorter.models.images.classify - INFO - Finished loading inception model.
2017-03-01 17:31:49,633 - candysorter.models.images.classify - INFO - Loading transfer model...
2017-03-01 17:31:50,008 - candysorter.models.images.classify - INFO - Finished loading transfer model.
 * Debugger is active!
 * Debugger pin code: 162-045-942
192.168.40.183 - - [01/Mar/2017 17:31:52] "GET /learn HTTP/1.1" 304 -
192.168.40.183 - - [01/Mar/2017 17:31:52] "GET /static/css/reset.css HTTP/1.1" 304 -
192.168.40.183 - - [01/Mar/2017 17:31:52] "GET /static/css/style.css HTTP/1.1" 304 -
192.168.40.183 - - [01/Mar/2017 17:31:52] "GET /static/css/anim.css HTTP/1.1" 304 -
192.168.40.183 - - [01/Mar/2017 17:31:52] "GET /static/js/learn.js HTTP/1.1" 304 -
192.168.40.183 - - [01/Mar/2017 17:31:53] "GET /learn HTTP/1.1" 304 -
2017-03-01 17:31:58,881 - candysorter.views.api - INFO - === Capture step 1: id=8248071993708614, session=20170301_173158_8248071993708614 ===
2017-03-01 17:31:58,881 - candysorter.views.api - INFO - Capturing image.
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/brainpad/opencv_from_git/opencv/modules/imgproc/src/color.cpp, line 9748
2017-03-01 17:31:58,882 - candysorter.views.api - WARNING -   Retrying: 1 times.
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/brainpad/opencv_from_git/opencv/modules/imgproc/src/color.cpp, line 9748
2017-03-01 17:31:58,982 - candysorter.views.api - WARNING -   Retrying: 2 times.
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/brainpad/opencv_from_git/opencv/modules/imgproc/src/color.cpp, line 9748
2017-03-01 17:31:59,083 - candysorter.views.api - WARNING -   Retrying: 3 times.
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/brainpad/opencv_from_git/opencv/modules/imgproc/src/color.cpp, line 9748
2017-03-01 17:31:59,183 - candysorter.views.api - WARNING -   Retrying: 4 times.
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/brainpad/opencv_from_git/opencv/modules/imgproc/src/color.cpp, line 9748
2017-03-01 17:31:59,284 - candysorter.views.api - WARNING -   Retrying: 5 times.
2017-03-01 17:31:59,384 - candysorter.views.api - ERROR - Unexpected error.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/brainpad/FindYourCandy/webapp/candysorter/views/api.py", line 88, in wrapper
    return f(*args, **kwargs)
  File "/home/brainpad/FindYourCandy/webapp/candysorter/views/api.py", line 268, in capture
    img = _capture_image()
  File "/home/brainpad/FindYourCandy/webapp/candysorter/views/api.py", line 416, in _capture_image
    raise Exception('Failed to capture image.')
Exception: Failed to capture image.
192.168.40.183 - - [01/Mar/2017 17:31:59] "POST /api/capture HTTP/1.1" 500 -

Thoughts?

Thanks!

**Comment by MFennig** [comment]
@rindai87 did not know if you had any ideas to this?

**Comment by rindai87** [comment]
It seems to be a focus issue. Can you execute setup/camera_tune.py again?

**Comment by max-hana** [comment]
I'm going to look at this more close after I reach my office.

But in general, you can't to have two processes accessing one camera.
and chmod is also needed prior to the execution.

**Comment by MFennig** [comment]
I have no issue with the focus, was able to run everything properly but still stuck with the same error.

**Comment by max-hana** [comment]
We are trying to reproduce your problem.

The error says that marker is not detected.  Since you reported the focus is ok, we're looking for other posibilities.

Meanwhile, could you access to "http://localhost:18000/_capture" and see if the 4 markers are actually visible in your eyes ?

**Comment by max-hana** [comment]
Looks like we found what you did (or didn't).

First, you didn't set environment variables needed to execute `python2 run.py`.
This error happens when you forgot to define `FLASK_ENV`. And there are a several other variables needed to work properly. see the [webapp/README.md](https://github.com/BrainPad/FindYourCandy/tree/master/webapp).

Second, you didn't run webapp from uWSGI as described in [webapp/README.md](https://github.com/BrainPad/FindYourCandy/tree/master/webapp).
If you just use uWSGI as recommended, this may not happen because variables are already defined in webapp.ini for uWSGI to start python.

**Comment by MFennig** [comment]
So I ran through and did a triple check on the webapp/README.md and still running into the same issue. Camera is tuned properly and still running into this road block. Any other things I could try?

**Comment by MFennig** [comment]
@max-hana i tried loading: http://localhost:18000/_capture and i get this as the error:

The image "http://localhost:18000/_capture" can not be displayed because it has errors.

**Comment by MFennig** [comment]
@max-hana @rindai87 
I did notice if I set
export FLASK_ENV='dev'
then the python2 run.py works but still fails at the camera.

if I run
export FLASK_ENV='prd'
the python2 run.py does not execute at all

**Comment by max-hana** [comment]
@MFennig 
So, you executed both webapp and robot-arm from command line?

If that is the case, you need to stop all uwsgi and nginx services.

> i tried loading: http://localhost:18000/_capture and i get this as the error:
> The image "http://localhost:18000/_capture" can not be displayed because it has errors.

Please check the following:
- You have only one camera connected to the linux box.
- ls -l /dev/video0 shows crwxrwxrwx . (you need chmod 777 for every reboot)
- camera_tune.py is closed/exited before running webapp.


>if I run
>export FLASK_ENV='prd'
>the python2 run.py does not execute at all

Assuming you're executing the following commands.
```sh
export FLASK_ENV='prd' 
cd /home/brainpad/FindYourCandy/webapp/
python2 run.py 
```

Running with `prd` will eliminate messages on terminal.
Therefore you better look at the log file instead of terminal. 
```sh
# Use another terminal and then type
tail -f /home/brainpad/FindYourCandy/webapp/logs/app.log
```
As mentioned in [setup/troubleshooting.md](https://github.com/BrainPad/FindYourCandy/tree/master/setup/troubleshooting.md) you have to wait for about 3,4 minutes before you can access on port 18000, otherwise you get error on your browser.

Important!
When you demo, please use uwsgi  because `python2 run.py` uses flask's web server which seems to be less stable.

**Comment by rindai87** [comment]
As @max-hana said, do you run some processes at the same time?

1. Stop or Kill all process about camera
2. Execute `python2 run.py` for debugging
3. Execute process from uwsgi for production

Please check also @max-hana 's advise.

**Comment by MFennig** [comment]
@rindai87 @max-hana 

So yes working thru the 'prd' and 'dev', the logs and terminal both show the same issue. Something I would like to point out on the issue above is this line:

OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/brainpad/opencv_from_git/opencv/modules/imgproc/src/color.cpp, line 9748

I was wondering if there is something that is causing that in particular? This could be what is actually screwing up.

**Comment by max-hana** [comment]
Maybe thats true....  but If you install opencv as instructed, there should be no error.

When installing opencv from source, it is pretty much affected by what libs you installed ahead.
We double tested from Ubuntu installation followed by exact command lines as documented from scratch.

Here is our cv2.so file size.
brainpad:~$ ls -l /usr/local/lib/python2.7/dist-packages/cv2.so
-rw-r--r-- 1 root staff 3710408 Feb 21 16:39 /usr/local/lib/python2.7/dist-packages/cv2.so

[cv2.zip](https://github.com/BrainPad/FindYourCandy/files/818274/cv2.zip)

It's Saturday morning in japan and I need to get going ;-) Good luck!

**Comment by rindai87** [comment]
@MFennig How about your status?

**Comment by rindai87** [comment]
We confirmed your setup didn't follow the correct procedure.
