### ISSUE TITLE
Dobot Offline

### ISSUE THREAD

**Issue by MFennig** [BrainPad/FindYourCandy#7]
Hi guys,

We have been working on getting everything setup. We have properly installed the Linux Box, we have also got the camera_tune.py to work. We are currently running into an issue where the robot_tune.py is returning this:

"dobot offline"

Now if we "sudo chmod 777 /dev/ttyUSB0", we then receive this new error:
"unpack requires a string argument of length 38"
"dobot offline"

What are your thoughts on this?

**Comment by max-hana** [comment]
Hi,

It seems like your dobot is not responding correctly. I tested 3 dobots; 2 dobots did work right away and one didn't. 

I recommend you to update the firmware of dobot by using DobotStudio on windows PC.
When you connect it to your PC and start DobotStudio, it will guide you to upgrade.

If it still doesn't work after upgrade, try to rename the dobot from the device menu of DobotStudio and name it 'dobot'.

Once it gets work, it always keep working. That's what I see.

Be sure that you are getting the right DobotStudio for your Dobot Magician.
( http://dobot.cc/download-center/dobot-magician.html )
And don't forget to chmod after recabling USB to linux box.

**Comment by MFennig** [comment]
That worked like a charm! Thank you again!

One last question I had for you, I am working through the process of configuring the webapp and when running the line "python2 run.py", I am getting this error back.

2017-02-28 12:13:12,815 - google.auth.transport._http_client - DEBUG - Making request: GET http://169.254.169.254
2017-02-28 12:13:15,813 - google.auth.compute_engine._metadata - INFO - Compute Engine Metadata server unavailable.
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    app = create_app()
  File "/home/brainpad/FindYourCandy/webapp/candysorter/app.py", line 22, in create_app
    _configure_blueprints(app)
  File "/home/brainpad/FindYourCandy/webapp/candysorter/app.py", line 35, in _configure_blueprints
    from candysorter.views.api import api
  File "/home/brainpad/FindYourCandy/webapp/candysorter/views/api.py", line 26, in <module>
    from candysorter.models.images.detect import CandyDetector, detect_labels
  File "/home/brainpad/FindYourCandy/webapp/candysorter/models/images/detect.py", line 13, in <module>
    vision_client = vision.Client()
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/client.py", line 162, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/client.py", line 118, in __init__
    project = self._determine_default(project)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/client.py", line 131, in _determine_default
    return _determine_default_project(project)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/_helpers.py", line 180, in _determine_default_project
    _, project = google.auth.default()
  File "/usr/local/lib/python2.7/dist-packages/google/auth/_default.py", line 282, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or
explicitly create credential and re-run the application. For more
information, please see
https://developers.google.com/accounts/docs/application-default-credentials.

Now I have the JSON file in the same location that it should be based on the webapp.ini, but I am still generating this error. Any reason you could think of?

**Comment by rindai87** [comment]
@MFennig resolved this issue?

**Comment by MFennig** [comment]
@rindai87 resolved with update of firmware thanks.
