### ISSUE TITLE
Not a gzipped file

### ISSUE THREAD

**Issue by MFennig** [BrainPad/FindYourCandy#8]
Hey y'all,

So working through your webapp.md and we are trying to run the "python2 run.py" and we are running into this issue:

Traceback (most recent call last):
  File "run.py", line 14, in <module>
    app = create_app()
  File "/home/brainpad/FindYourCandy/webapp/candysorter/app.py", line 22, in create_app
    _configure_blueprints(app)
  File "/home/brainpad/FindYourCandy/webapp/candysorter/app.py", line 38, in _configure_blueprints
    app.register_blueprint(api)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 64, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 951, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/usr/local/lib/python2.7/dist-packages/flask/blueprints.py", line 154, in register
    deferred(state)
  File "/home/brainpad/FindYourCandy/webapp/candysorter/views/api.py", line 48, in record
    text_analyzer.init()
  File "/home/brainpad/FindYourCandy/webapp/candysorter/models/texts.py", line 38, in init
    self._load_model()
  File "/home/brainpad/FindYourCandy/webapp/candysorter/models/texts.py", line 46, in _load_model
    self.model = gensim.models.Word2Vec.load_word2vec_format(self.model_file, binary=True)
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/word2vec.py", line 1173, in load_word2vec_format
    header = utils.to_unicode(fin.readline(), encoding=encoding)
  File "/usr/lib/python2.7/gzip.py", line 464, in readline
    c = self.read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file

We have cloned and tried downloading the files from here: https://github.com/mmihaltz/word2vec-GoogleNews-vectors

Any thoughts would be helpful.

Thanks!

**Comment by rindai87** [comment]
Did you download the gzip file from [google drive](https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?usp=sharing) ?

You should download the gzip file from Google drive because the file is too large. github does't host the file itself. 

This note is written on [README.md](https://github.com/mmihaltz/word2vec-GoogleNews-vectors/blob/master/README.md).

**Comment by max-hana** [comment]
Hi, 

The size of GoogleNews-vectors-negative300.bin.gz must be 1,647,046,227 bytes for this moment.
Are you sure you downloaded the whole file?

If you clone that project on github, you will get the file clobbered.
Reading the comments in the referering page, there is a link to download that file.
( Don't let your browser to automatically unzip the file, especially when you try to download with Mac.)

**Comment by rindai87** [comment]
@MFennig resolved this issue ?

**Comment by MFennig** [comment]
@rindai87 this did thank you
