### ISSUE TITLE
Socket Error

### ISSUE THREAD

**Issue by MFennig** [BrainPad/FindYourCandy#9]
Hey,

So trying to run "pyhton2 run.py" and when I do, I am getting this error in return:

Traceback (most recent call last):
  File "run.py", line 17, in <module>
    app.run(host=args.host, port=args.port)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 708, in run_simple
    inner()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 670, in inner
    fd=fd)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 564, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 476, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

Now I have tried to see whats on the port but was not successful. Any ideas?

Thanks!

**Comment by rindai87** [comment]
Error message seems to say that you have a process which uses the same port as flask.
You should check process and port on your machine, and kill it.

See also: http://stackoverflow.com/questions/41393384/flask-running-issue-socket-error-errno-98-address-already-in-use

**Comment by MFennig** [comment]
@rindai87  I tried to kill the port but it says "no such process"

**Comment by rindai87** [comment]
Hmm, can you share your operation command and result? It might be help for you.

**Comment by MFennig** [comment]
@rindai87 was able to close all ports thanks!
